export const base = {
  section: "w-full min-w-0",
  head: "mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between sm:gap-4",
  title: "m-0 font-[var(--native-font-display)] text-[1.0625rem] font-semibold tracking-[-0.04em] text-[var(--native-foreground)]",
  sub: "mt-0.5 max-w-[64ch] text-[0.8125rem] leading-[1.6] text-[var(--native-muted)]",
  tabs: "inline-flex max-w-full flex-wrap items-center gap-1 rounded-[var(--native-radius-full)] border border-[color:color-mix(in_oklab,var(--native-border)_38%,transparent)] bg-[color:color-mix(in_oklab,var(--native-surface)_76%,var(--native-panel))] p-[0.1875rem] shadow-[var(--native-shadow-sm)]",
  tab: "inline-flex cursor-pointer items-center whitespace-nowrap rounded-[var(--native-radius-full)] border-none px-3 py-[0.375rem] text-[0.8125rem] font-medium transition-all",
  tabOff: "bg-transparent text-[var(--native-muted)] hover:bg-[color-mix(in_oklab,var(--native-panel)_76%,transparent)] hover:text-[var(--native-foreground)]",
  tabOn: "bg-[var(--native-primary)] text-[var(--native-primary-foreground)] shadow-[0_8px_18px_-12px_color-mix(in_oklab,var(--native-primary)_65%,transparent)] hover:bg-[var(--native-primary-hover)] hover:text-[var(--native-primary-foreground)]",
  shell: "overflow-hidden rounded-[var(--native-radius-lg)] border border-[color:color-mix(in_oklab,var(--native-border)_42%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_84%,var(--native-bg-subtle))] p-3 shadow-[var(--native-shadow-sm)] sm:p-4",
  toolbar: "mb-3.5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between sm:gap-4",
  toolbarTitle: "m-0 font-[var(--native-font-display)] text-[0.9875rem] font-semibold tracking-[-0.03em] text-[var(--native-foreground)]",
  toolbarSub: "mt-0.5 max-w-[62ch] text-[0.8125rem] leading-[1.55] text-[var(--native-muted)]",
  toolbarActs: "flex w-full flex-wrap items-center gap-1.5 sm:w-auto sm:justify-end",
  searchWrap: "relative w-full sm:w-auto",
  searchIcon: "pointer-events-none absolute left-2 top-1/2 h-[13px] w-[13px] -translate-y-1/2 text-[var(--native-dim)]",
  search: "h-[1.9375rem] w-full min-w-0 rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_oklab,var(--native-border)_48%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_88%,var(--native-bg-subtle))] pl-7 pr-2.5 text-[0.8125rem] text-[var(--native-foreground)] outline-none transition-[border-color,box-shadow,background-color] placeholder:text-[var(--native-dim)] focus:border-[var(--native-primary)] focus:shadow-[0_0_0_3px_color-mix(in_oklab,var(--native-primary)_10%,transparent)] sm:w-44",
  btn: "inline-flex h-[1.9375rem] items-center justify-center gap-[0.3rem] rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_oklab,var(--native-border)_48%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_82%,var(--native-bg-subtle))] px-2.5 text-[0.8125rem] font-medium text-[var(--native-muted)] transition-all hover:border-[color:color-mix(in_oklab,var(--native-border-strong)_34%,transparent)] hover:bg-[var(--native-surface)] hover:text-[var(--native-foreground)]",
  btnPrimary: "border-[var(--native-primary)] bg-[var(--native-primary)] text-[var(--native-primary-foreground)] hover:border-[var(--native-primary-hover)] hover:bg-[var(--native-primary-hover)]",
  badge: "inline-flex items-center rounded-[var(--native-radius-full)] bg-[var(--native-secondary)] px-2.5 py-1 text-[12px] font-semibold uppercase tracking-[0.06em] text-[var(--native-secondary-foreground)]",
  sheet: "!p-0",
  sheetBody: "h-full max-w-none overflow-y-auto",
} as const