export const card = {
  statGrid: "grid grid-cols-1 gap-2.5 sm:grid-cols-2 xl:grid-cols-4",
  statCard: "flex items-center gap-3 rounded-[var(--native-radius-lg)] border border-[color:color-mix(in_oklab,var(--native-border)_42%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_84%,var(--native-bg-subtle))] px-4 py-3.5 shadow-[var(--native-shadow-sm)] transition-[box-shadow,transform,border-color] hover:-translate-y-px hover:border-[color:color-mix(in_oklab,var(--stat-accent)_20%,transparent)] hover:shadow-[var(--native-shadow-md)]",
  statIcon: "flex h-9 w-9 shrink-0 items-center justify-center rounded-[var(--native-radius-md)] border border-[color:color-mix(in_oklab,var(--stat-accent)_16%,transparent)] bg-[var(--stat-bg)] shadow-[inset_0_1px_0_color-mix(in_oklab,white_42%,transparent)] [&_[data-component=icon]]:text-[var(--stat-accent)] [&_[data-slot=icon-svg]]:text-[var(--stat-accent)]",
  statLabel: "text-[12px] font-medium uppercase tracking-[0.08em] text-[var(--native-muted)]",
  statValue: "m-0 text-[1.25rem] font-extrabold leading-[1.2] text-[var(--native-foreground)] [font-variant-numeric:tabular-nums]",
  cshell: "rounded-[1.25rem] border border-[color:color-mix(in_oklab,var(--native-border)_42%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_84%,var(--native-bg-subtle))] p-3 shadow-[var(--native-shadow-sm)] sm:p-4",
  pill: "inline-flex items-center gap-0.5 rounded-[var(--native-radius-full)] px-2 py-0.5 text-[12px]",
  action: "inline-flex h-6 w-6 items-center justify-center rounded-[var(--native-radius-sm)] bg-transparent text-[var(--native-muted)] transition-all hover:bg-[var(--native-primary-soft)] hover:text-[var(--native-foreground)] disabled:cursor-not-allowed disabled:opacity-[var(--native-disabled-opacity)]",
  dashGrid: "grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4",
  dashGrid2: "grid grid-cols-1 gap-3 sm:grid-cols-2",
  dashGrid3: "grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3",
  dashCard: "flex min-w-0 flex-col rounded-[var(--native-radius-md)] border border-[color:color-mix(in_oklab,var(--native-border)_44%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_88%,var(--native-bg-subtle))] px-4 py-3.5 shadow-[var(--native-shadow-sm)] transition-all hover:-translate-y-px hover:border-[color:color-mix(in_oklab,var(--native-primary)_18%,transparent)] hover:shadow-[var(--native-shadow-md)]",
  dashHead: "mb-1.5 flex items-center justify-between gap-2",
  dashName: "min-w-0 flex-1 truncate text-[0.8125rem] font-semibold text-[var(--native-foreground)]",
  dashSlug: "mb-1.5 truncate text-[12px] text-[var(--native-muted)]",
  dashDesc: "mb-2 min-h-[2.125em] flex-1 overflow-hidden text-[0.8125rem] leading-[1.5] text-[var(--native-muted)] [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]",
  dashStatus: "mb-2 flex items-center gap-1.5 text-[12px]",
  dashDot: "h-1.5 w-1.5 shrink-0 rounded-full",
  dashPulse: "animate-pulse",
  dashFoot: "flex items-center justify-end gap-0.5 border-t border-[color:color-mix(in_srgb,var(--native-border)_8%,transparent)] pt-2",
  filterBar: "mb-3 flex flex-wrap gap-1",
  filterBtn: "inline-flex items-center rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_oklab,var(--native-border)_44%,transparent)] bg-[color:color-mix(in_oklab,var(--native-panel)_80%,transparent)] px-3 py-[0.3125rem] text-[0.8125rem] font-medium text-[var(--native-muted)] transition-all hover:border-[color:color-mix(in_oklab,var(--native-border-strong)_34%,transparent)] hover:text-[var(--native-foreground)]",
  filterBtnOn: "border-[var(--native-primary)] bg-[color-mix(in_oklab,var(--native-primary)_10%,transparent)] text-[var(--native-primary)]",
  platform: "mb-1.5 flex items-center gap-1.5 text-[12px] text-[var(--native-muted)] [&_[data-component=icon]]:h-3 [&_[data-component=icon]]:w-3 [&_[data-component=icon]]:opacity-50 [&_[data-slot=icon-svg]]:h-3 [&_[data-slot=icon-svg]]:w-3 [&_[data-slot=icon-svg]]:opacity-50",
  labels: "mb-2 flex flex-wrap gap-1",
  notifField: "mb-1 flex min-w-0 items-center gap-1 text-[0.8125rem] text-[var(--native-muted)] [&>strong]:text-[var(--native-foreground)]",
  notifTest: "inline-flex items-center gap-1 rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_srgb,var(--native-primary)_30%,transparent)] bg-transparent px-2.5 py-1 text-[0.8125rem] text-[var(--native-primary)] transition-all hover:bg-[color-mix(in_srgb,var(--native-primary)_8%,transparent)] disabled:cursor-not-allowed disabled:opacity-50",
  empty: "rounded-[var(--native-radius-lg)] border border-dashed border-[color:color-mix(in_srgb,var(--native-border)_20%,transparent)] px-6 py-8 text-center text-[0.8125rem] text-[var(--native-muted)] sm:px-8 sm:py-10",
} as const