#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const rootDir = path.resolve(__dirname, "../../..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const skipSkill = process.argv.includes("--skip-skill")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

// Generate builtin agents file before building
console.log("Generating builtin agents...")
await $`bun run script/generate-agents.ts`

// Generate builtin skills file before building (embedded version)
if (skipSkill) {
  console.log("Skipping builtin skills generation (--skip-skill)")
  const builtinTsFile = path.resolve(dir, "src/costrict/skill/builtin.ts")
  await Bun.write(builtinTsFile, `// This file is auto-generated by script/generate-skills.ts
// Do not edit manually
// Builtin skills skipped during build (--skip-skill)

export const BUNDLED_SKILLS: Record<string, Record<string, string>> = {}
export async function loadSkillFiles(skillName: string): Promise<Record<string, string>> { return {} }
export async function listSkillFiles(skillName: string): Promise<string[]> { return [] }
export async function loadSkillFile(skillName: string, filePath: string): Promise<string> { throw new Error(\`Skill not found: \${skillName}\`) }
export async function getBuiltinSkillVersion(skillName: string): Promise<string | undefined> { return undefined }
export async function getAllBuiltinSkillVersions(): Promise<Record<string, string>> { return {} }
export function listBuiltinSkills(): string[] { return [] }
export function isBuiltinSkill(name: string): boolean { return false }
export async function extractBundledSkill(skillName: string, targetDir: string): Promise<void> { throw new Error(\`Skill not found: \${skillName}\`) }
`)
} else {
  console.log("Generating builtin skills...")
  await $`bun run script/generate-skills.ts`
}

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}

for (const item of targets) {
    const name = [
      pkg.name,
      // changing to win32 flags npm for some reason
      item.os === "win32" ? "windows" : item.os,
      item.arch,
      item.avx2 === false ? "baseline" : undefined,
      item.abi === undefined ? undefined : item.abi,
    ]
      .filter(Boolean)
      .join("-")
    console.log(`building ${name}`)
    await $`mkdir -p dist/${name}/bin`

    const callGraphWorkerPath = "./src/costrict/tool/call-graph/worker.ts"
    const fileImportanceWorkerPath = "./src/costrict/tool/file-importance/worker.ts"
  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

    // Use platform-specific bunfs root path based on target OS
    const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
    const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

    await Bun.build({
      conditions: ["browser"],
      tsconfig: "./tsconfig.json",
      plugins: [solidPlugin],
      sourcemap: "external",
      compile: {
        autoloadBunfig: false,
        autoloadDotenv: false,
        autoloadTsconfig: true,
        autoloadPackageJson: true,
        target: name.replace(pkg.name, "bun") as any,
        outfile: `dist/${name}/bin/cs`,
        execArgv: [`--smol`, `--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
        windows: {},
      },
      entrypoints: ["./src/index.ts", parserWorker, workerPath, callGraphWorkerPath, fileImportanceWorkerPath],
      define: {
        COSTRICT_VERSION: `'${Script.version}'`,
        COSTRICT_COMMIT_HASH: `'${Script.commitHash}'`,
        COSTRICT_BUILD_TIME: `'${Script.buildTime}'`,
        OPENCODE_MIGRATIONS: JSON.stringify(migrations),
        OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
        COSTRICT_WORKER_PATH: workerPath,
        COSTRICT_CALL_GRAPH_WORKER_PATH: callGraphWorkerPath,
        COSTRICT_FILE_IMPORTANCE_WORKER_PATH: fileImportanceWorkerPath,
        COSTRICT_CHANNEL: `'${Script.channel}'`,
        COSTRICT_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      },
    })

    await $`rm -rf ./dist/${name}/bin/tui`
    await Bun.file(`dist/${name}/package.json`).write(
      JSON.stringify(
        {
          name,
          version: Script.version,
          os: [item.os],
          cpu: [item.arch],
        },
        null,
        2,
      ),
    )
    const readmeSrc = path.join(rootDir, "README.md")
    const readmeDest = path.join(dir, `dist/${name}/README.md`)
    await $`cp ${readmeSrc} ${readmeDest}`
    binaries[name] = Script.version
  }

export { binaries }
