#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import fsp from "fs/promises"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"

// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`https://models.dev/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = (${modelsData}) as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const targetKey = (item: { os: string; arch: "arm64" | "x64" }) => `${item.os}-${item.arch}`

const parseSize = (header: Uint8Array) => {
  const sizeBuf = Buffer.from(header.subarray(124, 136))
  const sizeEnd = sizeBuf.indexOf(0)
  const sizeStr = sizeBuf
    .subarray(0, sizeEnd === -1 ? 12 : sizeEnd)
    .toString("utf8")
    .trim()
  return parseInt(sizeStr, 8) || 0
}

const parseMode = (header: Uint8Array) => {
  const modeBuf = Buffer.from(header.subarray(100, 108))
  const modeEnd = modeBuf.indexOf(0)
  const modeStr = modeBuf
    .subarray(0, modeEnd === -1 ? 8 : modeEnd)
    .toString("utf8")
    .trim()
  return parseInt(modeStr, 8) || 0o644
}

const parseName = (header: Uint8Array) => {
  const nameEnd = Buffer.from(header).indexOf(0, 0)
  return Buffer.from(header.subarray(0, nameEnd === -1 ? 100 : nameEnd)).toString("utf8")
}

const extractTarGz = async (archivePath: string, destDir: string) => {
  const compressed = await Bun.file(archivePath).arrayBuffer()
  const tarData = Bun.gunzipSync(Buffer.from(compressed))
  const state = { offset: 0 }

  while (state.offset < tarData.length) {
    const header = tarData.subarray(state.offset, state.offset + 512)
    state.offset += 512

    if (header.every((b) => b === 0)) {
      const nextHeader = tarData.subarray(state.offset, state.offset + 512)
      if (nextHeader.length === 512 && nextHeader.every((b) => b === 0)) {
        return
      }
      continue
    }

    const name = parseName(header)
    const size = parseSize(header)
    const mode = parseMode(header)
    const typeFlag = String.fromCharCode(header[156] || 0x30)

    if (name && name !== "./" && name !== "/") {
      if (typeFlag === "5") {
        const dirPath = path.join(destDir, name)
        await fsp.mkdir(dirPath, { recursive: true })
      }

      if (typeFlag === "0" || typeFlag === "\x00") {
        const filePath = path.join(destDir, name)
        const fileData = tarData.subarray(state.offset, state.offset + size)
        await fsp.mkdir(path.dirname(filePath), { recursive: true })
        await Bun.write(filePath, fileData)
        await fsp.chmod(filePath, mode).catch(() => {})
      }
    }

    state.offset += size
    if (size % 512 !== 0) {
      state.offset += 512 - (size % 512)
    }
  }
}

const setExecutablePermissions = async (dir: string) => {
  const walk = async (currentDir: string): Promise<void> => {
    const entries = await fsp.readdir(currentDir, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name)

      if (entry.isDirectory()) {
        await walk(fullPath)
        continue
      }
      if (!entry.isFile()) continue

      const isExecutable =
        !entry.name.includes(".") ||
        entry.name.endsWith(".exe") ||
        entry.name === "pmd" ||
        entry.name === "pmd.bat" ||
        entry.name === "revive" ||
        entry.name === "biome" ||
        entry.name === "ruff" ||
        entry.name === "clang-tidy" ||
        entry.name === "rg" ||
        entry.name === "fd"

      if (!isExecutable) continue
      await fsp.chmod(fullPath, 0o755).catch(() => {})
    }
  }

  await walk(dir)
}

const extractLintResourcesForTarget = async (
  outRoot: string,
  item: {
    os: string
    arch: "arm64" | "x64"
  },
) => {
  const lintRoot = path.join(outRoot, "lint")
  const bundlesDir = path.join(lintRoot, "bundles")
  const bundles = await fsp.readdir(bundlesDir).catch(() => [])
  const key = targetKey(item)

  for (const bundleName of bundles) {
    if (!bundleName.endsWith(".tar.gz")) continue
    if (!bundleName.includes(key) && !bundleName.includes("universal")) continue
    const match = bundleName.match(/^lint-(.+?)-(?:[^-]+-[^-]+|universal)\.tar\.gz$/)
    if (!match) continue
    const tool = match[1]
    if (!tool) continue
    const dest = path.join(lintRoot, tool)
    await fsp.rm(dest, { recursive: true, force: true })
    await fsp.mkdir(dest, { recursive: true })
    await extractTarGz(path.join(bundlesDir, bundleName), dest)
    if (item.os !== "win32") {
      await setExecutablePermissions(dest)
    }
  }
}

const extractSearchResourcesForTarget = async (
  outRoot: string,
  item: {
    os: string
    arch: "arm64" | "x64"
  },
) => {
  const searchRoot = path.join(outRoot, "search")
  const bundlesDir = path.join(searchRoot, "bundles")
  const bundles = await fsp.readdir(bundlesDir).catch(() => [])
  const key = targetKey(item)

  for (const bundleName of bundles) {
    if (!bundleName.endsWith(".tar.gz")) continue
    if (!bundleName.includes(key)) continue
    const match = bundleName.match(/^precompiled-(.+?)-([^-]+)-([^-]+)\.tar\.gz$/)
    if (!match) continue
    const tool = match[1]
    if (!tool) continue
    const dest = path.join(searchRoot, tool)
    await fsp.rm(dest, { recursive: true, force: true })
    await fsp.mkdir(dest, { recursive: true })
    await extractTarGz(path.join(bundlesDir, bundleName), dest)
    if (item.os !== "win32") {
      await setExecutablePermissions(dest)
    }
  }
}

const prepareResourcesForTarget = async (
  name: string,
  item: {
    os: string
    arch: "arm64" | "x64"
  },
) => {
  const srcRoot = path.join(dir, "resources")
  const outRoot = path.join(dir, "dist", name, "resources")
  await fsp.rm(outRoot, { recursive: true, force: true })
  await fsp.cp(srcRoot, outRoot, { recursive: true })
  await extractLintResourcesForTarget(outRoot, item)
  await extractSearchResourcesForTarget(outRoot, item)
  await fsp.rm(path.join(outRoot, "lint", "bundles"), { recursive: true, force: true })
  await fsp.rm(path.join(outRoot, "search", "bundles"), { recursive: true, force: true })
}

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

if (targets.length === 0) {
  throw new Error(
    `No build targets selected for ${process.platform}-${process.arch}. Remove --single or update build targets.`,
  )
}

await $`rm -rf dist`

// Generate builtin agents file before building
console.log("Generating builtin agents...")
await $`bun run script/generate-agents.ts`

// Generate builtin components file before building
console.log("Generating builtin components...")
await $`bun run script/generate-components.ts`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  const coreInstall = await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`.nothrow()
  if (coreInstall.exitCode !== 0) {
    console.warn("[build] warning: failed to install @opentui/core for all targets, continuing with existing dependencies")
  }

  const watcherInstall = await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`.nothrow()
  if (watcherInstall.exitCode !== 0) {
    console.warn("[build] warning: failed to install @parcel/watcher for all targets, continuing with existing dependencies")
  }
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"
  const callGraphWorkerPath = "./src/costrict/tool/call-graph/worker.ts"
  const fileImportanceWorkerPath = "./src/costrict/tool/file-importance/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/costrict-cli`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath, callGraphWorkerPath, fileImportanceWorkerPath],
    define: {
      COSTRICT_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      COSTRICT_WORKER_PATH: workerPath,
      COSTRICT_CALL_GRAPH_WORKER_PATH: callGraphWorkerPath,
      COSTRICT_FILE_IMPORTANCE_WORKER_PATH: fileImportanceWorkerPath,
      COSTRICT_CHANNEL: `'${Script.channel}'`,
      COSTRICT_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await prepareResourcesForTarget(name, item)
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

export { binaries }
