#!/usr/bin/env bun

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const componentsDir = path.resolve(__dirname, "../src/costrict/agent/components")
const outputFile = path.resolve(__dirname, "../src/costrict/agent/components.ts")

async function generate() {
  const entries = await fs.readdir(componentsDir, { withFileTypes: true })
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith(".txt"))
    .map((e) => e.name)
    .sort()

  const imports = files
    .map((name, i) => `import COMPONENT_${i} from "./components/${name}"`)
    .join("\n")

  const entries2 = files
    .map((name, i) => {
      const key = name.replace(/\.txt$/, "")
      return `  "${key}": COMPONENT_${i},\n  "${name}": COMPONENT_${i}`
    })
    .join(",\n")

  const content = `// This file is auto-generated by script/generate-components.ts when building the CLI
// Do not edit manually

${imports}

export const COMPONENTS: Record<string, string> = {
${entries2},
}
`

  await fs.writeFile(outputFile, content, "utf-8")
  console.log(`Generated ${outputFile} with ${files.length} components`)
}

generate().catch(console.error)
