#!/usr/bin/env bun

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const agentDir = path.resolve(__dirname, "../src/costrict/agent")
const outputFile = path.resolve(__dirname, "../src/costrict/agent/builtin.ts")

async function generateBuiltinAgents() {
  const agentFiles: string[] = []

  // Only scan .txt files in the builtin directory
  const entries = await fs.readdir(agentDir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith(".txt")) {
      agentFiles.push(path.join(agentDir, entry.name))
    }
  }

  // Generate import statements
  const imports = agentFiles.map((file, index) => {
    const relativePath = path.relative(path.dirname(outputFile), file).replaceAll("\\", "/")
    return `import AGENT_${index} from "./${relativePath}"`
  }).join("\n")

  // Generate exports
  const exports = `export const BUILTIN_AGENTS = [\n${agentFiles.map((_, index) => `  AGENT_${index}`).join(",\n")}\n]`

  const content = `// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

${imports}

${exports}
`

  await fs.writeFile(outputFile, content, "utf-8")
  console.log(`Generated ${outputFile} with ${agentFiles.length} agents`)
}

generateBuiltinAgents().catch(console.error)
