export type MediaKind = "image" | "audio" | "svg";
type MediaValue = unknown;
export declare function normalizeMimeType(type: string | undefined): string | undefined;
export declare function fileExtension(path: string | undefined): string;
export declare function mediaKindFromPath(path: string | undefined): MediaKind | undefined;
export declare function isBinaryContent(value: MediaValue): boolean;
export declare function dataUrlFromMediaValue(value: MediaValue, kind: MediaKind): string | undefined;
export declare function svgTextFromValue(value: MediaValue): string | undefined;
export declare function hasMediaValue(value: MediaValue): boolean;
export {};
