// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

import AGENT_0 from "./locales/en/01-wiki-project-analyze.txt"
import AGENT_1 from "./locales/zh-CN/01-wiki-project-analyze.txt"
import AGENT_2 from "./locales/en/02-wiki-catalogue-design.txt"
import AGENT_3 from "./locales/zh-CN/02-wiki-catalogue-design.txt"
import AGENT_4 from "./locales/en/03-wiki-document-generate.txt"
import AGENT_5 from "./locales/zh-CN/03-wiki-document-generate.txt"
import AGENT_6 from "./locales/en/04-wiki-index-generation.txt"
import AGENT_7 from "./locales/zh-CN/04-wiki-index-generation.txt"
import AGENT_8 from "./locales/en/spec-design.txt"
import AGENT_9 from "./locales/zh-CN/spec-design.txt"
import AGENT_10 from "./locales/en/spec-plan-manager.txt"
import AGENT_11 from "./locales/zh-CN/spec-plan-manager.txt"
import AGENT_12 from "./locales/en/spec-plan.txt"
import AGENT_13 from "./locales/zh-CN/spec-plan.txt"
import AGENT_14 from "./locales/en/spec-requirement.txt"
import AGENT_15 from "./locales/zh-CN/spec-requirement.txt"
import AGENT_16 from "./locales/en/spec-task.txt"
import AGENT_17 from "./locales/zh-CN/spec-task.txt"
import AGENT_18 from "./locales/en/strict-plan.txt"
import AGENT_19 from "./locales/zh-CN/strict-plan.txt"
import AGENT_20 from "./locales/en/strict-spec.txt"
import AGENT_21 from "./locales/zh-CN/strict-spec.txt"
import AGENT_22 from "./locales/en/tdd.txt"
import AGENT_23 from "./locales/zh-CN/tdd.txt"

export type AgentEntry = {
  locales: Record<string, string>
  models?: Record<string, string>
}

export const BUILTIN_AGENTS: Record<string, AgentEntry> = {
  "01-wiki-project-analyze": { locales: { "en": AGENT_0, "zh-CN": AGENT_1 } },
  "02-wiki-catalogue-design": { locales: { "en": AGENT_2, "zh-CN": AGENT_3 } },
  "03-wiki-document-generate": { locales: { "en": AGENT_4, "zh-CN": AGENT_5 } },
  "04-wiki-index-generation": { locales: { "en": AGENT_6, "zh-CN": AGENT_7 } },
  "spec-design": { locales: { "en": AGENT_8, "zh-CN": AGENT_9 } },
  "spec-plan-manager": { locales: { "en": AGENT_10, "zh-CN": AGENT_11 } },
  "spec-plan": { locales: { "en": AGENT_12, "zh-CN": AGENT_13 } },
  "spec-requirement": { locales: { "en": AGENT_14, "zh-CN": AGENT_15 } },
  "spec-task": { locales: { "en": AGENT_16, "zh-CN": AGENT_17 } },
  "strict-plan": { locales: { "en": AGENT_18, "zh-CN": AGENT_19 } },
  "strict-spec": { locales: { "en": AGENT_20, "zh-CN": AGENT_21 } },
  "tdd": { locales: { "en": AGENT_22, "zh-CN": AGENT_23 } }
}
