// This file is auto-generated by script/generate-components.ts when building the CLI
// Do not edit manually

import COMPONENT_0 from "./components/agent-git-usage.txt"
import COMPONENT_1 from "./components/analyze-code-structure-guidelines.txt"
import COMPONENT_2 from "./components/clarify-detailed.txt"
import COMPONENT_3 from "./components/clarify-minimal.txt"
import COMPONENT_4 from "./components/clarify-moderate.txt"
import COMPONENT_5 from "./components/execute-quick-explore-task-usage.txt"
import COMPONENT_6 from "./components/fd-usage.txt"
import COMPONENT_7 from "./components/memory-bank-guidelines.txt"
import COMPONENT_8 from "./components/rg-usage.txt"

export const COMPONENTS: Record<string, string> = {
  "agent-git-usage": COMPONENT_0,
  "agent-git-usage.txt": COMPONENT_0,
  "analyze-code-structure-guidelines": COMPONENT_1,
  "analyze-code-structure-guidelines.txt": COMPONENT_1,
  "clarify-detailed": COMPONENT_2,
  "clarify-detailed.txt": COMPONENT_2,
  "clarify-minimal": COMPONENT_3,
  "clarify-minimal.txt": COMPONENT_3,
  "clarify-moderate": COMPONENT_4,
  "clarify-moderate.txt": COMPONENT_4,
  "execute-quick-explore-task-usage": COMPONENT_5,
  "execute-quick-explore-task-usage.txt": COMPONENT_5,
  "fd-usage": COMPONENT_6,
  "fd-usage.txt": COMPONENT_6,
  "memory-bank-guidelines": COMPONENT_7,
  "memory-bank-guidelines.txt": COMPONENT_7,
  "rg-usage": COMPONENT_8,
  "rg-usage.txt": COMPONENT_8,
}
