// This file is auto-generated by script/generate-skills.ts
// Do not edit manually
// Builtin skills skipped during build (--skip-skill)

export const BUNDLED_SKILLS: Record<string, Record<string, string>> = {}
export async function loadSkillFiles(skillName: string): Promise<Record<string, string>> { return {} }
export async function listSkillFiles(skillName: string): Promise<string[]> { return [] }
export async function loadSkillFile(skillName: string, filePath: string): Promise<string> { throw new Error(`Skill not found: ${skillName}`) }
export async function getBuiltinSkillVersion(skillName: string): Promise<string | undefined> { return undefined }
export async function getAllBuiltinSkillVersions(): Promise<Record<string, string>> { return {} }
export function listBuiltinSkills(): string[] { return [] }
export function isBuiltinSkill(name: string): boolean { return false }
export async function extractBundledSkill(skillName: string, targetDir: string): Promise<void> { throw new Error(`Skill not found: ${skillName}`) }
