// This file is auto-generated by script/generate-skills.ts
// Do not edit manually
// All skill files are embedded at build time for compiled builds



/**
 * Embedded skills - all skill files are embedded at build time
 */
export const BUNDLED_SKILLS: Record<string, Record<string, string>> = {
  "security-review": {

  }
}

/**
 * Get the embedded skill files for a skill
 */
export async function loadSkillFiles(skillName: string): Promise<Record<string, string>> {
  return BUNDLED_SKILLS[skillName] || {}
}

/**
 * Get all files in a skill directory (returns list of file paths)
 */
export async function listSkillFiles(skillName: string): Promise<string[]> {
  return Object.keys(BUNDLED_SKILLS[skillName] || {})
}

/**
 * Load a single skill file content
 */
export async function loadSkillFile(skillName: string, filePath: string): Promise<string> {
  const skillFiles = BUNDLED_SKILLS[skillName]
  if (!skillFiles) {
    throw new Error(`Skill not found: ${skillName}`)
  }
  const content = skillFiles[filePath]
  if (content === undefined) {
    throw new Error(`File not found in skill ${skillName}: ${filePath}`)
  }
  return content
}

/**
 * Get the version (commit SHA) for a specific builtin skill
 */
export async function getBuiltinSkillVersion(skillName: string): Promise<string | undefined> {
  const versions: Record<string, string> = {

  }
  return versions[skillName]
}

/**
 * Get all builtin skill versions
 */
export async function getAllBuiltinSkillVersions(): Promise<Record<string, string>> {
  return {

  }
}

/**
 * List all builtin skill names
 */
export function listBuiltinSkills(): string[] {
  return ["security-review"]
}

/**
 * Check if a skill is a builtin skill
 */
export function isBuiltinSkill(name: string): boolean {
  return ["security-review"].includes(name)
}

/**
 * Extract bundled skill to a target directory (used for installing to user cache)
 * This function writes embedded skill content to the target directory
 */
export async function extractBundledSkill(skillName: string, targetDir: string): Promise<void> {
  const { writeFile } = await import("fs/promises")
  const { join, dirname } = await import("path")
  const { mkdir } = await import("fs/promises")

  const skillFiles = BUNDLED_SKILLS[skillName]
  if (!skillFiles) {
    throw new Error(`Skill not found: ${skillName}`)
  }

  // Create target directory
  await mkdir(targetDir, { recursive: true })

  // Write all files
  for (const [relativePath, content] of Object.entries(skillFiles)) {
    const filePath = join(targetDir, relativePath)
    const fileDir = join(targetDir, dirname(relativePath))
    await mkdir(fileDir, { recursive: true })
    await writeFile(filePath, content, "utf-8")
  }
}
